/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface UPVoteTreasuryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "NATIVE"
      | "assetConfig"
      | "campaignAllowed"
      | "campaignAllowlistEnabled"
      | "feeReceiver"
      | "owner"
      | "rescueBNB"
      | "rescueToken"
      | "setAsset"
      | "setCampaignAllowed"
      | "setCampaignAllowlistEnabled"
      | "setFeeReceiver"
      | "transferOwnership"
      | "voteWithBNB"
      | "voteWithToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetConfigured"
      | "CampaignAllowed"
      | "CampaignAllowlistToggled"
      | "FeeReceiverUpdated"
      | "OwnershipTransferred"
      | "Rescue"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(functionFragment: "NATIVE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "assetConfig",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignAllowlistEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rescueBNB",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueToken",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAsset",
    values: [AddressLike, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCampaignAllowed",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setCampaignAllowlistEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeReceiver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voteWithBNB",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voteWithToken",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "NATIVE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assetConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignAllowlistEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rescueBNB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rescueToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCampaignAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCampaignAllowlistEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteWithBNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteWithToken",
    data: BytesLike
  ): Result;
}

export namespace AssetConfiguredEvent {
  export type InputTuple = [
    asset: AddressLike,
    enabled: boolean,
    minAmount: BigNumberish
  ];
  export type OutputTuple = [
    asset: string,
    enabled: boolean,
    minAmount: bigint
  ];
  export interface OutputObject {
    asset: string;
    enabled: boolean;
    minAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignAllowedEvent {
  export type InputTuple = [campaign: AddressLike, allowed: boolean];
  export type OutputTuple = [campaign: string, allowed: boolean];
  export interface OutputObject {
    campaign: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignAllowlistToggledEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeReceiverUpdatedEvent {
  export type InputTuple = [
    previousReceiver: AddressLike,
    newReceiver: AddressLike
  ];
  export type OutputTuple = [previousReceiver: string, newReceiver: string];
  export interface OutputObject {
    previousReceiver: string;
    newReceiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RescueEvent {
  export type InputTuple = [
    asset: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [asset: string, to: string, amount: bigint];
  export interface OutputObject {
    asset: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    campaign: AddressLike,
    voter: AddressLike,
    asset: AddressLike,
    amountPaid: BigNumberish,
    meta: BytesLike
  ];
  export type OutputTuple = [
    campaign: string,
    voter: string,
    asset: string,
    amountPaid: bigint,
    meta: string
  ];
  export interface OutputObject {
    campaign: string;
    voter: string;
    asset: string;
    amountPaid: bigint;
    meta: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UPVoteTreasury extends BaseContract {
  connect(runner?: ContractRunner | null): UPVoteTreasury;
  waitForDeployment(): Promise<this>;

  interface: UPVoteTreasuryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  NATIVE: TypedContractMethod<[], [string], "view">;

  assetConfig: TypedContractMethod<
    [arg0: AddressLike],
    [[boolean, bigint] & { enabled: boolean; minAmount: bigint }],
    "view"
  >;

  campaignAllowed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  campaignAllowlistEnabled: TypedContractMethod<[], [boolean], "view">;

  feeReceiver: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  rescueBNB: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  rescueToken: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAsset: TypedContractMethod<
    [asset: AddressLike, enabled: boolean, minAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCampaignAllowed: TypedContractMethod<
    [campaign: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setCampaignAllowlistEnabled: TypedContractMethod<
    [enabled: boolean],
    [void],
    "nonpayable"
  >;

  setFeeReceiver: TypedContractMethod<
    [newFeeReceiver: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  voteWithBNB: TypedContractMethod<
    [campaign: AddressLike, meta: BytesLike],
    [void],
    "payable"
  >;

  voteWithToken: TypedContractMethod<
    [
      campaign: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      meta: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "NATIVE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "assetConfig"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[boolean, bigint] & { enabled: boolean; minAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "campaignAllowed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "campaignAllowlistEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "feeReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rescueBNB"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rescueToken"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAsset"
  ): TypedContractMethod<
    [asset: AddressLike, enabled: boolean, minAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCampaignAllowed"
  ): TypedContractMethod<
    [campaign: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCampaignAllowlistEnabled"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeReceiver"
  ): TypedContractMethod<[newFeeReceiver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "voteWithBNB"
  ): TypedContractMethod<
    [campaign: AddressLike, meta: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "voteWithToken"
  ): TypedContractMethod<
    [
      campaign: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      meta: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AssetConfigured"
  ): TypedContractEvent<
    AssetConfiguredEvent.InputTuple,
    AssetConfiguredEvent.OutputTuple,
    AssetConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "CampaignAllowed"
  ): TypedContractEvent<
    CampaignAllowedEvent.InputTuple,
    CampaignAllowedEvent.OutputTuple,
    CampaignAllowedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignAllowlistToggled"
  ): TypedContractEvent<
    CampaignAllowlistToggledEvent.InputTuple,
    CampaignAllowlistToggledEvent.OutputTuple,
    CampaignAllowlistToggledEvent.OutputObject
  >;
  getEvent(
    key: "FeeReceiverUpdated"
  ): TypedContractEvent<
    FeeReceiverUpdatedEvent.InputTuple,
    FeeReceiverUpdatedEvent.OutputTuple,
    FeeReceiverUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Rescue"
  ): TypedContractEvent<
    RescueEvent.InputTuple,
    RescueEvent.OutputTuple,
    RescueEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "AssetConfigured(address,bool,uint256)": TypedContractEvent<
      AssetConfiguredEvent.InputTuple,
      AssetConfiguredEvent.OutputTuple,
      AssetConfiguredEvent.OutputObject
    >;
    AssetConfigured: TypedContractEvent<
      AssetConfiguredEvent.InputTuple,
      AssetConfiguredEvent.OutputTuple,
      AssetConfiguredEvent.OutputObject
    >;

    "CampaignAllowed(address,bool)": TypedContractEvent<
      CampaignAllowedEvent.InputTuple,
      CampaignAllowedEvent.OutputTuple,
      CampaignAllowedEvent.OutputObject
    >;
    CampaignAllowed: TypedContractEvent<
      CampaignAllowedEvent.InputTuple,
      CampaignAllowedEvent.OutputTuple,
      CampaignAllowedEvent.OutputObject
    >;

    "CampaignAllowlistToggled(bool)": TypedContractEvent<
      CampaignAllowlistToggledEvent.InputTuple,
      CampaignAllowlistToggledEvent.OutputTuple,
      CampaignAllowlistToggledEvent.OutputObject
    >;
    CampaignAllowlistToggled: TypedContractEvent<
      CampaignAllowlistToggledEvent.InputTuple,
      CampaignAllowlistToggledEvent.OutputTuple,
      CampaignAllowlistToggledEvent.OutputObject
    >;

    "FeeReceiverUpdated(address,address)": TypedContractEvent<
      FeeReceiverUpdatedEvent.InputTuple,
      FeeReceiverUpdatedEvent.OutputTuple,
      FeeReceiverUpdatedEvent.OutputObject
    >;
    FeeReceiverUpdated: TypedContractEvent<
      FeeReceiverUpdatedEvent.InputTuple,
      FeeReceiverUpdatedEvent.OutputTuple,
      FeeReceiverUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Rescue(address,address,uint256)": TypedContractEvent<
      RescueEvent.InputTuple,
      RescueEvent.OutputTuple,
      RescueEvent.OutputObject
    >;
    Rescue: TypedContractEvent<
      RescueEvent.InputTuple,
      RescueEvent.OutputTuple,
      RescueEvent.OutputObject
    >;

    "VoteCast(address,address,address,uint256,bytes32)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
