/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20__factory } from "./IERC20__factory";
export { Ownable__factory } from "./Ownable__factory";
export { UPVoteTreasury__factory } from "./UPVoteTreasury__factory";
