/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockRouter,
  MockRouterInterface,
} from "../../../contracts/mocks/MockRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "factory_",
        type: "address",
      },
      {
        internalType: "address",
        name: "wrapped_",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountToken",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountETH",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "LiquidityAdded",
    type: "event",
  },
  {
    inputs: [],
    name: "WETH",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountTokenDesired",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "addLiquidityETH",
    outputs: [
      {
        internalType: "uint256",
        name: "amountToken",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "liquidity",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60c03461007a57601f6102c738819003918201601f19168301916001600160401b0383118484101761007f57808492604094855283398101031261007a57610052602061004b83610095565b9201610095565b9060805260a05260405161021d90816100aa82396080518161019e015260a051816101e10152f35b600080fd5b634e487b7160e01b600052604160045260246000fd5b51906001600160a01b038216820361007a5756fe60806040818152600436101561001457600080fd5b600091823560e01c908163ad5c4648146101cd57508063c45a01551461018a5763f305d7191461004357600080fd5b60c0366003190112610186576001600160a01b03906004358281169190829003610182576024359260843590811680910361017e5781516323b872dd60e01b8152336004820152306024820152604481018590526020919082816064818a895af180156101745761010f575b50348501938486116100fb57606096507f3c69701a61c79a92ef9692903aaa0068bce8771361ecb09547391e4fb4df85378480518881523486820152a381519384523490840152820152f35b634e487b7160e01b87526011600452602487fd5b823d841161016d575b601f8101601f191682016001600160401b03811183821017610159578491839187528101031261015557518015150361015157386100af565b8580fd5b8680fd5b634e487b7160e01b89526041600452602489fd5b503d610118565b84513d89823e3d90fd5b8480fd5b8380fd5b5080fd5b5034610186578160031936011261018657517f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b8390346101865781600319360112610186577f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f3fea164736f6c6343000818000a";

type MockRouterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockRouterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockRouter__factory extends ContractFactory {
  constructor(...args: MockRouterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    factory_: AddressLike,
    wrapped_: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(factory_, wrapped_, overrides || {});
  }
  override deploy(
    factory_: AddressLike,
    wrapped_: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(factory_, wrapped_, overrides || {}) as Promise<
      MockRouter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockRouter__factory {
    return super.connect(runner) as MockRouter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockRouterInterface {
    return new Interface(_abi) as MockRouterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockRouter {
    return new Contract(address, _abi, runner) as unknown as MockRouter;
  }
}
